title: Health Buddy Research Summaries
url: https://ai-tech-institute.github.io
baseurl: /health_buddy_pages
theme: minima

collections:
  daily_reports:
    output: true
  weekly_summaries:
    output: true

header_pages:
  - index.md
  - topics.md
  - subscribe.md

subscribe_url: https://forms.gle/Ta9mc5NAsr4sYzsH8
