url: https://ai-tech-institute.github.io
baseurl: /health_buddy_pages
title: Health Buddy Research Summaries
theme: minima
collections:
  daily_reports:
    output: true
  weekly_summaries:
    output: true
